name: business_savvy

description: business_savvy


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  event_bus: ^2.0.0
  shared_preferences: ^2.5.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  flutter:
    sdk: flutter
  http: ^1.1.0  # 使用最新版本
  go_router: ^7.0.0  # 使用最新版本
  dio: ^5.3.3  # 添加 dio 依赖
  http_parser: ^4.0.1
  english_words: ^4.0.0
  provider: ^6.0.0
  fluttertoast: ^8.2.12
  loading_indicator: ^3.1.1
  flutter_inappwebview: ^6.0.0
  intl: ^0.18.1  # 添加这一行
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.1
  flutter_web_plugins:
    sdk: flutter
  photo_view: ^0.15.0
  carousel_slider: ^5.0.0
  adaptive_dialog: ^1.9.0
  getwidget: ^6.0.0
  rive: ^0.13.20
  flutter_staggered_animations: ^1.1.0  # 检查最新版本
  custom_refresh_indicator: ^4.0.1
  bot_toast: ^4.1.3
  flutter_echarts: ^2.5.0
  screenshot: ^3.0.0
  path_provider: ^2.1.3
  image_gallery_saver: ^2.0.3
  url_launcher: ^6.2.5
  # 地址和位置相关依赖
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/brand/
    - assets/map/json/
    - assets/map/json/province/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"